version: '3'

services:
  amir_backend:
    build:
      context: .
    command: /app/server
    ports:
      - 3000:3000
    depends_on:
      - mongo
    networks:
      - frontend
      - backend 

  mongo:
    image: mongo
    command: 'mongod --smallfiles'
    volumes:
      - 'mongodata:/data/db'
    expose:
      - 27017

  web:
    image: amir_frontend
    command: /bin/bash /ember-proxy-service.sh
    ports:
      - 80:80
    depends_on:
      - amir_backend
  networks:
  frontend:
    driver: frontend
  backend:
    driver: backend

volumes:
  mongodata:

